version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "3001:3001"
    depends_on:
      - backend

  designer:
    build: ./designer
    container_name: designer
    ports:
      - "3002:3002"
    depends_on:
      - backend

  consumer:
    build: ./home
    container_name: home
    ports:
      - "3003:3003"
    depends_on:
      - backend

  printing_provider:
    build: ./printing_provider
    container_name: printing_provider
    ports:
      - "3004:3004"
    depends_on:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Change this to a strong password!
      MYSQL_DATABASE: postocard          # Default database name
      MYSQL_USER: postocard_user         # Custom user
      MYSQL_PASSWORD: postocard_pass     # Custom user password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: