version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "3001:3001"
    depends_on:
      - backend

  designer:
    build: ./designer
    container_name: designer
    ports:
      - "3002:3002"
    depends_on:
      - backend

  consumer:
    build: ./home
    container_name: home
    ports:
      - "3003:3003"
    depends_on:
      - backend

  printing_provider:
    build: ./printing_provider
    container_name: printing_provider
    ports:
      - "3004:3004"
    depends_on:
      - backend
