import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import { Providers } from "@/components/providers";
import AuthProvider from "@/features/auth/components/auth-provider";

>>>>>>> 41e2ed688c58c9ff04da4c17fe54ab47913bf8bf
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Posto Card | Designer",
  description: "Posto Card",
>>>>>>> 41e2ed688c58c9ff04da4c17fe54ab47913bf8bf
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {children}
=======
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
>>>>>>> 41e2ed688c58c9ff04da4c17fe54ab47913bf8bf
      </body>
    </html>
  );
}
